# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sprinternship-dal-2025/google-internship', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sprinternship-dal-2025/google-internship']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'google-internship', '--image', 'gcr.io/sprinternship-dal-2025/google-internship', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated'] # Adjust region and other args as needed

options:
  # Use one of these:
  logging: CLOUD_LOGGING_ONLY
